name: Test and build backend

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - ".github/workflows/build-backend.yml"

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build --no-daemon
        shell: bash